### ISSUE TITLE
CVMFS: turn off autofs  and mount cvmfs manually 

### ISSUE THREAD

**Issue by spigad** [Cloud-PG/ansible-role-cms_config#1]
take a look here: 
https://cernvm.cern.ch/portal/filesystem/docker

also, remember to remove the cron.

**Comment by ciangottinim** [comment]
Proposed fix:

`- name: Creates CVMFS mountpoint
  file: path=/cvmfs/cms.cern.ch state=directory

- name: mount CVMFS
  mount:
    path: /cvmfs/cms.cern.ch
    src: cms.cern.ch
    fstype: cvmfs
    opts: noatime
    state: present`

**Comment by ciangottinim** [comment]
Done.

```
- name: Creates CVMFS mountpoint
  file: path=/cvmfs/cms.cern.ch state=directory owner=cvmfs group=cvmfs recurse=yes
  tags: cms_config
  
- name: mount CVMFS
  command: mount -t cvmfs cms.cern.ch /cvmfs/cms.cern.ch/
  tags: cms_config
```
